import 'package:flutter/material.dart';

//Colors
const white = Colors.white;
const facebookColor = Color(0xff3b5997);
const purple = Colors.purple;
const black = Colors.black;
const indigo = Colors.indigo;
const red = Colors.red;
const transparent = Colors.transparent;
const grey = Colors.grey;
const lightIndigo = Color(0xFFE8EAF6);
//Text
const appName = "Chat App";
const singIn = "Sing-in";
const googlSsingIn = "Google Sing-in";
const faceSingIn = "Facebook Sing-in";
const emailSingIn = "E mail Sing-in";
const guestSingIn = "guest sign-in";
const emailPasswordSingIn = "Login with email and password!";
const loginn = "Login";
const registerr = "Register";
const emailText = "E mail";
const enterEmail = "enter  E email";
const passwordText = "Password";
const enterPassword = "Enter password";
const userLoginEror = "User login error!";
const registerContenterrorText = "This user does not exist in the db";
const ok = "OK";
const loginError = "Login error!";
const loginContentError = "This Email is already in use! Try different e-mail!";
const enterMessage = "Enter message!";
const profil = "Profile ";
const exit = "exit";
const takePicture = "take a picture";
const selectFromGallery = "Select from Gallery";
const titleUsername = "Username";
const enterUsername = "enter username";
const saveText = "Save";
const logOut = "Log out";
const logOutContent = "Are you sure we want to log out?";
const yes = "Yes";
const no = "No";
const successfulTransaction = "Successful transaction";
const changesSaved = "Changes saved";
const usernameContentError =
    "UserName already exists, try a different username!";
const profilephoto = "Profile image uploaded successfully!";
const profilePhotoContent = "profile picture processing has been completed.";
const delete = "Delete";
const noChatFound = "No chat found!";
const chats = "Chats";
const users = "Users ";
const noRegisterUserFound = "No registered users found!";
const chatDelete = "Chat deleted successfully";
const chaNotDelete = "An error occurred while deleting the chat";
