// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmwg4s623Sp6cv9Ma5jpyaRdgNalES4TU',
    appId: '1:544594598267:web:84bf93e6e08f34886345de',
    messagingSenderId: '544594598267',
    projectId: 'fir-crashlytics-21097',
    authDomain: 'fir-crashlytics-21097.firebaseapp.com',
    storageBucket: 'fir-crashlytics-21097.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHoQ5d4vKPYkWqtuQAVwtmMRklc6i6TWc',
    appId: '1:544594598267:android:d5c9c0349931811e6345de',
    messagingSenderId: '544594598267',
    projectId: 'fir-crashlytics-21097',
    storageBucket: 'fir-crashlytics-21097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hvmrKDceBHFls1EB3TPY8npIvdgT7O4',
    appId: '1:544594598267:ios:9d41697e5b38ef676345de',
    messagingSenderId: '544594598267',
    projectId: 'fir-crashlytics-21097',
    storageBucket: 'fir-crashlytics-21097.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrashlyticsUsage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hvmrKDceBHFls1EB3TPY8npIvdgT7O4',
    appId: '1:544594598267:ios:b35dc314fa3d4ef46345de',
    messagingSenderId: '544594598267',
    projectId: 'fir-crashlytics-21097',
    storageBucket: 'fir-crashlytics-21097.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrashlyticsUsage.RunnerTests',
  );
}
